sudo: false

language: elixir

elixir:
  - 1.2.0

env: MIX_ENV=Test

otp_release:
  - 18.0

script:
  - MIX_ENV=test mix coveralls.travis

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
